build:
  version: "1.0"

accounts:
  message: "Welcome to SumanthGollaprolu-Bank accounts related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@SumanthGollaprolu-Bank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384