build:
  version: "3.0"

cards:
  message: "Welcome to SumanthGollaprolu-Bank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@SumanthGollaprolu-Bank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932